<?php

namespace AppBundle\Repository;

/**
 * ordersEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ordersEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
